swagger: "2.0"
info:
  version: "1.0.0"
  title: "Inventory management"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/api/v1"
tags:
  - name: "inventory"
  - name: "location"
  - name: "ItemType"
  - name: "user"
schemes:
  - "http"
paths:
  /inventory:
    post:
      tags:
        - "inventory"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: inventory
          schema:
            $ref: "#/definitions/InventoryInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Inventory"
        404:
          description: Inventory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /inventory/{id}:
    get:
      tags:
        - "inventory"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Inventory"
        404:
          description: Inventory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    delete:
      tags:
        - "inventory"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
        404:
          description: Inventory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    patch:
      tags:
        - "inventory"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Inventory"
        404:
          description: Inventory not found
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /location:
    get:
      tags:
        - "location"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Location"
        404:
          description: location not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    post:
      tags:
        - "location"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: location
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/LocationInput"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Location"
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /location/{id}:
    get:
      tags:
        - "location"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Location"
        404:
          description: location not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    patch:
      tags:
        - "location"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
        - in: body
          name: location
          schema:
            $ref: "#/definitions/LocationInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/Location"
        404:
          description: location not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    delete:
      tags:
        - "location"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
        404:
          description: location not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /location/{locationId}/inventory:
    get:
      tags:
        - "location"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: locationId
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/Inventory"
        404:
          description: location not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /itemType:
    get:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/ItemType"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    post:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: location
          schema:
            $ref: "#/definitions/ItemTypeInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/ItemType"
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server
          schema:
            $ref : "#/definitions/ErrorResponse"
  /itemType/{id}:
    get:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/ItemType"
        404:
          description: item type not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    patch:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
        - in: body
          name: ItemType
          schema:
            $ref: "#/definitions/ItemTypeInput"
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/ItemType"
        404:
          description: item type not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
    delete:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: id
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
        404:
          description: item type not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        422:
          description: Invalid Input
          schema:
            $ref : "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /itemType/{itemId}/inventory:
    get:
      tags:
        - "ItemType"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: itemId
          type: string
          required: true
      responses:
        200:
          description: "successful operation"
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/ItemType"
        404:
          description: item type not exists
          schema:
            $ref: '#/definitions/ErrorResponse'
        503:
          description: Server Error
          schema:
            $ref : "#/definitions/ErrorResponse"
  /user:
    get:
      tags:
        - user
      produces:
        - application/json
      responses:
        200:
          description: Successful list user
          schema:
            type: object
            properties:
              data:
                type: array
                items:
                  $ref: "#/definitions/User"
        503:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      tags:
        - user
      parameters:
        - in: body
          name: User
          schema:
            $ref: "#/definitions/UserInput"
      produces:
        - application/json
      responses:
        200:
          description: Successful Create user
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/User"
        422:
          description: Invalid Input
          schema:
            $ref: "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /user/{user}:
    get:
      tags:
        - user
      parameters:
        - name: user
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Successful get user
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/User"
        404:
          description: User not exists
          schema:
            $ref: "#/definitions/ErrorResponse"
        503:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    patch:
      tags:
        - user
      parameters:
        - name: user
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Successful update user
          schema:
            type: object
            properties:
              data:
                $ref: "#/definitions/User"
        404:
          description: User not exists
          schema:
            $ref: "#/definitions/ErrorResponse"
        503:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      tags:
        - user
      parameters:
        - name: user
          in: path
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: "successful operation"
        404:
          description: user not exists
          schema:
            $ref: "#/definitions/ErrorResponse"
        422:
          description: Invalid Input
          schema:
            $ref: "#/definitions/Error422Response"
        503:
          description: Server Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  Inventory:
    type: "object"
    properties:
      id:
        type: "string"
      itemType:
        type: "string"
      location:
        type: "string"
      lastSeenTime:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
          - "STOCK"
          - "IN_USE"
          - "REPAIR"
  InventoryInput:
    type: "object"
    properties:
      itemType:
        type: "string"
      location:
        type: "string"
      status:
        type: "string"
        description: "Order Status"
        enum:
          - "STOCK"
          - "IN_USE"
          - "REPAIR"
  Location:
    type: "object"
    properties:
      id:
        type: "string"
      name:
        type: "string"
  LocationInput:
    type: "object"
    properties:
      name:
        type: "string"
  ItemType:
    type: "object"
    required:
      - "name"
    properties:
      id:
        type: "string"
      name:
        type: "string"
        example: "doggie"
      description:
        type: "string"
  ItemTypeInput:
    type: "object"
    required:
      - "name"
    properties:
      name:
        type: "string"
        example: "doggie"
      description:
        type: "string"
  User:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
      name:
        type: string
  UserInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
  Error422Response:
    type: "object"
    properties:
      code:
        type: "string"
      massage:
        type: "string"
      params:
        type: "object"
  ErrorResponse:
    type: "object"
    properties:
      code:
        type: "string"
      massage:
        type: "string"
      params:
        type: "object"